name: build

on:
  push:
    branches:
      - main

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      uses: RoiSoleil/flatten-p2-repo@main
      with:
        repository-path: "sdfjkhskdjfh"
