name: build

on:
  push:
    branches:
      - main

jobs:
  test-action:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Flatten P2 repository
      uses: RoiSoleil/flatten-p2-repo@main
      with:
        repository-path: "repository"
